# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache = false
# Game Properties
minecraft_version = 26.1.2
loader_version = 0.19.3
loom_version = 1.17-SNAPSHOT
# Mod Properties
mod_id = lost_relics
mod_name = Lost Relics
mod_description = Find unique and powerful artifacts in the ancient structures of the world!
version = 26.1-r7
group = moriyashiine.lost-relics
# Common Dependencies
fabric_api_version = 0.155.2+26.1.2
strawberrylib_version = 26.1-r9
ohmega_version = 1.6.0-beta.16-mc26.1.2
nycto_version = 26.1-b11
# Chenille
release_type = release
modrinth_id = xF60FXqO
curseforge_id = 953036
curseforge_versions = 26.1; 26.1.1; 26.1.2
mr_embeddeds = cardinal-components-api
cf_embeddeds = cardinal-components-api
